export default {
  AAW: require('./assets/img/map/AAW_25.png'),
  ABW: require('./assets/img/map/ABW_25.png'),
  ATW: require('./assets/img/map/ATW_25.png'),
  FCW: require('./assets/img/map/FCW_25.png'),
  HMW: require('./assets/img/map/HMW_25.png'),
  Idle: require('./assets/img/map/Idle.png'),
  LLDW: require('./assets/img/map/LDW_L_25.png'),
  RLDW: require('./assets/img/map/LDW_R_25.png'),
  OFFline: require('./assets/img/map/OFFline.png'),
  ONline: require('./assets/img/map/ONline.png'),
  PCW: require('./assets/img/map/PCW_25.png'),
  Select: require('./assets/img/map/Select.png'),
  SPW: require('./assets/img/map/SPW_25.png'),
  UFCW: require('./assets/img/map/UFCW_25.png'),
  VB: require('./assets/img/map/VBW_25.png'),
}
